[2025-04-23T00:53:23.000+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dwh_mart.mart_gsheet scheduled__2025-04-21T03:30:00+00:00 [queued]>
[2025-04-23T00:53:23.015+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dwh_mart.mart_gsheet scheduled__2025-04-21T03:30:00+00:00 [queued]>
[2025-04-23T00:53:23.015+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-04-23T00:53:23.040+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): mart_gsheet> on 2025-04-21 03:30:00+00:00
[2025-04-23T00:53:23.051+0000] {standard_task_runner.py:60} INFO - Started process 297 to run task
[2025-04-23T00:53:23.056+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_dwh_mart', 'mart_gsheet', 'scheduled__2025-04-21T03:30:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dags_etl.py', '--cfg-path', '/tmp/tmp45bn8m_q']
[2025-04-23T00:53:23.060+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask mart_gsheet
[2025-04-23T00:53:23.137+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_dwh_mart.mart_gsheet scheduled__2025-04-21T03:30:00+00:00 [running]> on host a896c9815708
[2025-04-23T00:53:23.263+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dwh_mart' AIRFLOW_CTX_TASK_ID='mart_gsheet' AIRFLOW_CTX_EXECUTION_DATE='2025-04-21T03:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-21T03:30:00+00:00'
[2025-04-23T00:53:23.265+0000] {Mart_GoogleSheet.py:91} INFO - Processing worksheet: Sheet1
[2025-04-23T00:53:23.266+0000] {Mart_GoogleSheet.py:35} INFO - Extracting data using query: SELECT * FROM mart_user_purchase;
[2025-04-23T00:53:23.268+0000] {Mart_GoogleSheet.py:41} ERROR - Error extracting data: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-23T00:53:23.269+0000] {Mart_GoogleSheet.py:96} ERROR - Failed to process Sheet1: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-23T00:53:23.269+0000] {Mart_GoogleSheet.py:91} INFO - Processing worksheet: Sheet2
[2025-04-23T00:53:23.269+0000] {Mart_GoogleSheet.py:35} INFO - Extracting data using query: SELECT * FROM mart_user_repurchase;
[2025-04-23T00:53:23.270+0000] {Mart_GoogleSheet.py:41} ERROR - Error extracting data: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-23T00:53:23.271+0000] {Mart_GoogleSheet.py:96} ERROR - Failed to process Sheet2: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-23T00:53:23.271+0000] {Mart_GoogleSheet.py:91} INFO - Processing worksheet: Sheet3
[2025-04-23T00:53:23.271+0000] {Mart_GoogleSheet.py:35} INFO - Extracting data using query: SELECT * FROM mart_revenue_period;
[2025-04-23T00:53:23.273+0000] {Mart_GoogleSheet.py:41} ERROR - Error extracting data: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-23T00:53:23.273+0000] {Mart_GoogleSheet.py:96} ERROR - Failed to process Sheet3: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-23T00:53:23.274+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-04-23T00:53:23.288+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_dwh_mart, task_id=mart_gsheet, execution_date=20250421T033000, start_date=20250423T005323, end_date=20250423T005323
[2025-04-23T00:53:23.349+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-23T00:53:23.377+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
