[2025-04-23T00:53:18.401+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dwh_mart.dwh_mart_user_repurchase scheduled__2025-04-21T03:30:00+00:00 [queued]>
[2025-04-23T00:53:18.434+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dwh_mart.dwh_mart_user_repurchase scheduled__2025-04-21T03:30:00+00:00 [queued]>
[2025-04-23T00:53:18.435+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-04-23T00:53:18.475+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): dwh_mart_user_repurchase> on 2025-04-21 03:30:00+00:00
[2025-04-23T00:53:18.493+0000] {standard_task_runner.py:60} INFO - Started process 287 to run task
[2025-04-23T00:53:18.503+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_dwh_mart', 'dwh_mart_user_repurchase', 'scheduled__2025-04-21T03:30:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/dags_etl.py', '--cfg-path', '/tmp/tmpvd5kxhnd']
[2025-04-23T00:53:18.510+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask dwh_mart_user_repurchase
[2025-04-23T00:53:18.653+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_dwh_mart.dwh_mart_user_repurchase scheduled__2025-04-21T03:30:00+00:00 [running]> on host a896c9815708
[2025-04-23T00:53:18.845+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dwh_mart' AIRFLOW_CTX_TASK_ID='dwh_mart_user_repurchase' AIRFLOW_CTX_EXECUTION_DATE='2025-04-21T03:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-21T03:30:00+00:00'
[2025-04-23T00:53:18.848+0000] {DWH_MartUserRepurchase.py:30} INFO - Extracting data using query: 
            SELECT o.order_id, o.user_id, u.user_first_name || ' ' || u.user_last_name as user_name 
            FROM fact_orders o
            INNER JOIN dim_user u
            ON o.user_id = u.user_id;
        
[2025-04-23T00:53:18.851+0000] {DWH_MartUserRepurchase.py:36} ERROR - Error extracting data: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-23T00:53:18.851+0000] {DWH_MartUserRepurchase.py:82} ERROR - process failed: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-23T00:53:18.852+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-04-23T00:53:18.868+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=etl_dwh_mart, task_id=dwh_mart_user_repurchase, execution_date=20250421T033000, start_date=20250423T005318, end_date=20250423T005318
[2025-04-23T00:53:18.923+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-23T00:53:18.974+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
